// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxx-U',
    appId: '1:xxxxxxxxxxxxxxx:web:xxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxx',
    projectId: 'streetwyze23',
    authDomain: 'streetwyze23.firebaseapp.com',
    storageBucket: 'streetwyze23.appspot.com',
    measurementId: 'G-xxxxxxxxx',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxx',
    appId: '1:639685484911:android:xxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxx',
    projectId: 'streetwyze23',
    storageBucket: 'streetwyze23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxx:ios:xxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxx',
    projectId: 'streetwyze23',
    storageBucket: 'streetwyze23.appspot.com',
    androidClientId: 'xxxxxxxxx-xxxxxxxxxx.apps.googleusercontent.com',
    iosClientId: 'xxxxxxxxxx-xxxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetWyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxx',
    appId: '1:639685484911:ios:xxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxx',
    projectId: 'streetwyze23',
    storageBucket: 'streetwyze23.appspot.com',
    androidClientId: 'xxxxxxx-xxxxxxxxx.apps.googleusercontent.com',
    iosClientId: 'xxxxxxxxx-xxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetWyze.RunnerTests',
  );
}
