// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQi7HCQeQnVFTwGW0zkO_X9ITtA5xi-U',
    appId: '1:639685484911:web:e812dd077a2f7df6b1889a',
    messagingSenderId: '639685484911',
    projectId: 'streetwyze23',
    authDomain: 'streetwyze23.firebaseapp.com',
    storageBucket: 'streetwyze23.appspot.com',
    measurementId: 'G-3F8B0ZLGE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJF4Snkj48LZ3uzWfPkv93ZM_qyC4GJJ8',
    appId: '1:639685484911:android:720c730c1e560609b1889a',
    messagingSenderId: '639685484911',
    projectId: 'streetwyze23',
    storageBucket: 'streetwyze23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjsYpC4ehPWvBkyd8USz7NrxYD5ncBTLQ',
    appId: '1:639685484911:ios:fdaa773f45e64123b1889a',
    messagingSenderId: '639685484911',
    projectId: 'streetwyze23',
    storageBucket: 'streetwyze23.appspot.com',
    androidClientId: '639685484911-gsuai5sfpka8odmrel7e4eg1bl3f9gb0.apps.googleusercontent.com',
    iosClientId: '639685484911-qvf1n8i2j9jbgrouchi8lm276eqchr17.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetWyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjsYpC4ehPWvBkyd8USz7NrxYD5ncBTLQ',
    appId: '1:639685484911:ios:e83fc415b3a43cbab1889a',
    messagingSenderId: '639685484911',
    projectId: 'streetwyze23',
    storageBucket: 'streetwyze23.appspot.com',
    androidClientId: '639685484911-gsuai5sfpka8odmrel7e4eg1bl3f9gb0.apps.googleusercontent.com',
    iosClientId: '639685484911-efo93q56m8o59nr443m4b96o4fdiaauh.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetWyze.RunnerTests',
  );
}
